---
  - hosts: MyServer
    become: yes
    tasks:
      - name: Set Hostname to Permanent
        lineinfile:
          path: /etc/cloud/cloud.cfg
          regex: '^#?preserve_hostname:'
          line: 'preserve_hostname: true'
          backrefs: yes

      - name: Disable Hostname Change
        lineinfile:
          path: /etc/cloud/cloud.cfg.d/01_debian_cloud.cfg
          regex: '^manage_etc_hosts:'
          line: 'manage_etc_hosts: false'
          backrefs: yes

      - name: Set Time Zone        
      # shell: timedatectl set-timezone America/Vancouver
        timezone:
          name: America/Vancouver

      - name: Disable IPv6 with sysctl
        sysctl: name={{ item }} value=1 state=present reload=yes
        with_items:
          - net.ipv6.conf.all.disable_ipv6
          - net.ipv6.conf.default.disable_ipv6
          - net.ipv6.conf.lo.disable_ipv6

      - name: Debian | blacklist ipv6 in modprobe
        lineinfile:
          dest: /etc/modprobe.d/blacklist.conf
          line: 'blacklist ipv6'
          mode: '0644'
          create: yes
